window.PART8 = [
  {
    id: "8-1",
    ch: "8",
    no: "01",
    title: "模拟卷总览：卷面结构、环境与提交规范",
    dur: "15分钟",
    tag: "真题演练·模拟题",
    lead: "本节把整套模拟卷（与三小时技能考同构）的卷首信息过一遍：你的比赛机上有什么、每个任务用什么环境、交卷时文件叫什么。这些信息分布在卷面开头，漏看一条就丢分。",
    points: [
      "PC 机 Anaconda 三个虚拟环境：MLearn（任务一二：数据准备 + 机器学习）、deepLearn（任务三：深度学习）、labelimg（任务三的数据标注），环境已预装对应依赖",
      "服务器已用 Ollama 预部署 qwen3:14b-q8_0、deepseek-r1:14b-qwen-distill-q8_0 和 bge-m3（向量）；Dify 1.9.2 位于 C:\\Program Files\\dify\\dify-1.9.2，初始未启动需自己启动：先开 Docker Desktop，再在 dify 目录的 docker 文件夹执行 docker compose 启动命令，然后浏览器打开 localhost/install",
      "Dify 登录：邮箱 AIServerTest001@Test.com，账号 AIServerTest001，密码 AIServerTest001；在 Dify 里添加本地大模型要选已预装的 Ollama 模型供应商插件，基础 URL 按卷面提示填写",
      "matplotlib 中文防乱码固定两行：plt.rcParams['font.sans-serif'] = ['SimHei'] 和 plt.rcParams['axes.unicode_minus'] = False，卷面特别提示",
      "五个任务互相独立，不关联：先做会做的、分值大的；文件名必须严格按卷面命名（如清洗后电商用户数据集.csv、shop1_N.csv、traffic_sign_detect_model.pt），结果保存在指定位置",
      "数据都在试题压缩包里：traffic_sign_dataset（训练/验证/测试三份，测试集用于推理）、EcommerceUser.csv、ShortVideo.csv、SweeperRobot.csv、SweeperAfterSale.csv",
    ],
    tip: "模拟题的交通标志数据集是直行、停车让行、左转、右转 4 类（video_id 与 yaml 的 nc=4 names 对应）。现场拿到数据集，第一件事看 yaml 与标签格式，确认类别数，再动手。",
  },
  {
    id: "8-2",
    ch: "8",
    no: "02",
    title: "模拟题任务一·子任务一：数据清洗（在线可跑）",
    dur: "25分钟",
    tag: "真题演练·在线运行",
    lead: "EcommerceUser.csv 共 150 条电商用户数据，含真实异常：用户编号重复、性别含『男性』『女 1』等脏值、支付方式含『微信支付』『支 fu 宝』『现金』等格式异常、年龄和是否复购有空值。子任务一要求：去重、修正性别、筛掉支付方式异常、输出异常数量与前十条、按消费金额分等级并统计数量、保存清洗后文件。下面 demo 用与比赛一致的代码在线跑真实数据。",
    points: [
      "要求逐条对齐：utf-8 读取 → drop_duplicates(subset='用户编号', keep='first') → 性别非『男/女』统一修正 → 支付方式只留『微信/支付宝/银行卡』并统计删除量 → 前十条 → 消费金额 0-5000 低 / 5001-20000 中 / 20001+ 高 → 保存不保留索引",
      "关键得分点：去重要指明 subset；修正用 replace 映射一次写完；等级用 pd.cut 或 np.select，标签要用卷面文字『低消费』等",
      "文件名必须一字不差：清洗后电商用户数据集.csv",
    ],
    demos: [
      {
        title: "清洗全流程（真实数据在线运行）",
        code: "import pandas as pd\n\n# 需求1 读取，utf-8\ndf = pd.read_csv('EcommerceUser.csv', encoding='utf-8')\nprint('原始行数:', len(df))\n\n# 需求2 去重（仅保留第一条）\ndf = df.drop_duplicates(subset='用户编号', keep='first')\nprint('去重后行数:', len(df))\n\n# 需求3 修正性别异常值\nsex_map = {'男 1': '男', '男性': '男', '女性': '女', '女姓': '女', '女 2': '女'}\ndf['性别'] = df['性别'].replace(sex_map)\nprint('性别取值:', df['性别'].unique())\n\n# 需求4 筛掉支付方式非标准值\nstd_pay = ['微信', '支付宝', '银行卡']\nbad_pay = df[~df['支付方式'].isin(std_pay)]\nprint('支付方式格式异常数量:', len(bad_pay))\ndf = df[df['支付方式'].isin(std_pay)]\n\n# 需求5 清洗后前十条\nprint(df.head(10).to_string())\n\n# 需求6 消费等级\nbins = [0, 5000, 20000, float('inf')]\nlabels = ['低消费', '中消费', '高消费']\ndf['消费等级'] = pd.cut(df['消费金额'], bins=bins, labels=labels, right=True)\nprint(df['消费等级'].value_counts())\n\n# 需求7 保存\n# df.to_csv('清洗后电商用户数据集.csv', index=False)",
      },
    ],
  },
  {
    id: "8-3",
    ch: "8",
    no: "03",
    title: "模拟题任务一·子任务二：空值补全（在线可跑）",
    dur: "20分钟",
    tag: "真题演练·在线运行",
    lead: "子任务二接着清洗后的数据：年龄列和是否复购列存在空值，数量以你实际读到的为准。要求：年龄用中位数填充、是否复购用众数填充；输出补全前缺失数量；输出补全后年龄的均值、标准差、最大值、最小值；新增用户活跃度字段（消费频次≥30 高活跃 / 10-29 中活跃 / 0-9 低活跃）并输出占比（保留 2 位小数）。",
    points: [
      "填充方式必须和卷面一致：数值列中位数（median），类别列众数（mode），混用就扣分",
      "统计特征用 describe() 截取或用 series.mean()/std()/max()/min() 单独输出，四舍五入要求看卷面；占比 round(2) 保留两位",
      "活跃度规则边界：≥30 高、10-29 中、0-9 低，用 pd.cut 或 np.select 时注意区间可重合处理为右闭",
      "空值处理前先 isna().sum() 输出两个列的缺失数量，这是明确的得分点",
    ],
    demos: [
      {
        title: "空值补全 + 活跃度占比（在线运行）",
        code: "import pandas as pd\n\n# 模拟：直接从清洗结果继续（真实数据在线可直接读）\ndf = pd.read_csv('EcommerceUser.csv')\ndf = df.drop_duplicates(subset='用户编号', keep='first')\n\n# 需求2 补全前的缺失数量\nprint('年龄缺失:', df['年龄'].isna().sum())\nprint('是否复购缺失:', df['是否复购'].isna().sum())\n\n# 年龄：中位数填充；是否复购：众数填充\ndf['年龄'] = df['年龄'].fillna(df['年龄'].median())\nmode_val = df['是否复购'].mode()[0]\ndf['是否复购'] = df['是否复购'].fillna(mode_val)\n\n# 需求3 补全后年龄统计特征\nprint('均值 %.2f 标准差 %.2f 最大 %.2f 最小 %.2f' % (\n    df['年龄'].mean(), df['年龄'].std(), df['年龄'].max(), df['年龄'].min()))\n\n# 需求4 活跃度分布\nimport numpy as np\nconds = [df['消费频次'] >= 30, (df['消费频次'] >= 10) & (df['消费频次'] <= 29), df['消费频次'] <= 9]\nchoices = ['高活跃', '中活跃', '低活跃']\ndf['活跃度'] = np.select(conds, choices, default='低活跃')\nratio = (df['活跃度'].value_counts() / len(df) * 100).round(2)\nprint(ratio)\n\n# 需求5 保存（比赛时取消注释）\n# df.to_csv('补全后电商用户数据集.csv', index=False)",
      },
    ],
  },
  {
    id: "8-4",
    ch: "8",
    no: "04",
    title: "模拟题任务一·子任务三：数据脱敏（在线可跑）",
    dur: "20分钟",
    tag: "真题演练·在线运行",
    lead: "子任务三在补全后的数据上做脱敏：姓名（单字名保留原字，双字名保留首字，三字名首字加两个星号）、手机号（保留前 2 位和后 3 位，中间 6 位变星号）、所在城市（只保留省份或直辖市）；输出前十条；会员等级编码（普通 0 / 白银 1 / 黄金 2 / 铂金 3）输出前 5 条；保存脱敏文件。",
    points: [
      "姓名脱敏要按字数分别处理：单字、双字、三字及以上三种情况，逻辑写清楚",
      "手机号：前 2 位 + 6 个星号 + 后 3 位（如 13812345678 → 13******678）",
      "城市：split 省份关键词（浙江省/北京市 等），用字符串 startswith 判断省维名称；数据里的城市是虚构的（如『浙江省成都市锦江区』），脱敏只取『省/直辖市』部分",
      "会员等级编码用 replace 或 map 一次性完成，不要逐行循环",
      "规程点名「掩码或哈希」两种脱敏方式。掩码看得见格式，哈希不可逆、适合身份证号这类唯一标识：hashlib.sha256 转 64 位十六进制；同一条数据哈希值恒定，验证可用性时按哈希值互查和去重仍有效",
      "保存名：脱敏后电商用户数据集.csv，不保留索引",
    ],
    demos: [
      {
        title: "三类脱敏 + 等级编码（在线运行）",
        code: "import pandas as pd\n\ndf = pd.read_csv('EcommerceUser.csv')\ndf = df.drop_duplicates(subset='用户编号', keep='first')\ndf['年龄'] = df['年龄'].fillna(df['年龄'].median())\ndf['是否复购'] = df['是否复购'].fillna(df['是否复购'].mode()[0])\n\n# 姓名脱敏：单字保留，双字保留首字，三字及以上 首字+**\ndef mask_name(name):\n    n = str(name)\n    if len(n) == 1:\n        return n\n    if len(n) == 2:\n        return n[0]\n    return n[0] + '**'\n\ndf['姓名'] = df['姓名'].apply(mask_name)\n\n# 手机号脱敏：前2 + 6星 + 后3\ndef mask_phone(p):\n    p = str(p)\n    return p[:2] + '******' + p[-3:]\n\ndf['手机号'] = df['手机号'].apply(mask_phone)\n\n# 城市脱敏：只保留省/直辖市\nprovince_kw = ['省', '市']  # 北京市/上海市/浙江省 等\ndef keep_province(city):\n    c = str(city)\n    for kw in ['省', '市']:\n        i = c.find(kw)\n        if i != -1:\n            return c[:i + 1]\n    return c\n\ndf['所在城市'] = df['所在城市'].apply(keep_province)\n\n# 需求3 脱敏后前十条\nprint(df.head(10).to_string())\n\n# 需求4 会员等级编码\nlevel_map = {'普通': 0, '白银': 1, '黄金': 2, '铂金': 3}\ndf['会员等级编码'] = df['会员等级'].map(level_map)\nprint(df.head(5)[['姓名', '手机号', '所在城市', '会员等级', '会员等级编码']].to_string())\n\n# 方式二：哈希脱敏（规程点名「掩码或哈希」；身份证等唯一标识建议哈希）\nimport hashlib\ndf['手机号哈希'] = df['手机号'].apply(lambda p: hashlib.sha256(str(p).encode()).hexdigest())\nprint(df.head(3)[['手机号', '手机号哈希']].to_string())\n\n# 需求5 保存（比赛时取消注释）\n# df.to_csv('脱敏后电商用户数据集.csv', index=False)",
      },
    ],
  },
  {
    id: "8-5",
    ch: "8",
    no: "05",
    title: "模拟题任务二·子任务一：文本预处理与 TF-IDF 特征提取（在线可跑）",
    dur: "25分钟",
    tag: "真题演练·在线运行",
    lead: "ShortVideo.csv 有 200 条短视频数据（video_id / title / desc / label，label 0 生活、1 美食、2 游戏、3 美妆）。子任务一要求：合并 title 与 desc 为 content；去除所有非中文字符（只保留汉字、数字、。，！？）；合并多余空格；用 TfidfVectorizer（max_features=1500, stop_words='english'）向量化；输出矩阵形状；特征名保存为 txt 并打印前 15 个；词频 Top10。",
    points: [
      "清洗顺序固定：合并 → 去非中文 → 去空格，正则一步到位后用 re.sub 处理空白",
      "TfidfVectorizer 参数按卷面：max_features=1500、stop_words='english'（中文文本下等价仅过滤极少英文停用词，不影响）",
      "特征名列表用 vectorizer.get_feature_names_out() 获取（sklearn 1.3+），前 15 个打印",
      "词频统计用 collections.Counter 对合并后的 content 分词统计，输出 Top10 词汇及次数",
      "矩阵.toarray() 形状 (200, min(1500, 词数))，打印即可",
    ],
    demos: [
      {
        title: "预处理 + TF-IDF + 词频 Top10（在线运行）",
        pkgs: "scikit-learn",
        code: "import pandas as pd\nimport re\nfrom sklearn.feature_extraction.text import TfidfVectorizer\nfrom collections import Counter\n\ndf = pd.read_csv('ShortVideo.csv')\n\n# 需求2 合并标题与描述\nclean = []\nfor _, r in df.iterrows():\n    t = str(r['title']) + ' ' + str(r['desc'])\n    t = re.sub(r'[^\\u4e00-\\u9fa50-9。，！？]', '', t)  # 去除非汉字数字标点\n    t = re.sub(r'\\s+', ' ', t).strip()  # 合并空格\n    clean.append(t)\ndf['content'] = clean\n\n# 需求3 TF-IDF 特征\nvec = TfidfVectorizer(max_features=1500, stop_words='english')\nX = vec.fit_transform(df['content'])\nprint('特征矩阵形状:', X.shape)\n\n# 需求4/5 特征名\nnames = vec.get_feature_names_out() if hasattr(vec, 'get_feature_names_out') else vec.get_feature_names()\nprint('前15个特征名:', list(names[:15]))\nwith open('tfidf_feature_names.txt', 'w', encoding='utf-8') as f:\n    f.write('\\n'.join(names))\n\n# 需求6 词频 Top10\nwords = re.findall(r'[\\u4e00-\\u9fa5]{1,}', ' '.join(df['content']))\nprint('词频 Top10:', Counter(words).most_common(10))\n\n# 保存中间结果供子任务二使用（比赛时）\n# df.to_csv('clean_shortvideo.csv', index=False)",
      },
    ],
  },
  {
    id: "8-6",
    ch: "8",
    no: "06",
    title: "模拟题任务二·子任务二：随机森林四分类 + 混淆矩阵解读（在线可跑）",
    dur: "25分钟",
    tag: "真题演练·在线运行",
    lead: "以 TF-IDF 特征矩阵为输入、label 为标签，做 75/25 划分（random_state=24、分层抽样），训练随机森林多分类模型；输出准确率和加权 F1（保留 4 位小数）；输出混淆矩阵，并解读两类误判：美食被误判为游戏的数量、美妆被漏判为生活的数量。",
    points: [
      "划分固定参数：train_test_split(test_size=0.25, random_state=24, stratify=y)，stratify 必须带，是明确要求",
      "模型参数可自由调试，但演示版用默认 + n_estimators；评分按输出格式给分：round(score, 4)",
      "混淆矩阵用 sklearn.metrics.confusion_matrix 或 ConfusionMatrixDisplay；解读时按矩阵行列定位：行是真实标签、列是预测标签",
      "美妆(3)→生活(0)：confusion[3][0]；美食(1)→游戏(2)：confusion[1][2]",
      "f1 用 average='weighted'；accuracy 直接用 accuracy_score",
    ],
    demos: [
      {
        title: "随机森林四分类完整流程（在线运行）",
        pkgs: "scikit-learn",
        code: "import pandas as pd\nimport re\nfrom sklearn.feature_extraction.text import TfidfVectorizer\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import accuracy_score, f1_score, confusion_matrix\n\ndf = pd.read_csv('ShortVideo.csv')\nclean = []\nfor _, r in df.iterrows():\n    t = str(r['title']) + ' ' + str(r['desc'])\n    t = re.sub(r'[^\\u4e00-\\u9fa50-9。，！？]', '', t)\n    t = re.sub(r'\\s+', ' ', t).strip()\n    clean.append(t)\ndf['content'] = clean\n\nvec = TfidfVectorizer(max_features=1500, stop_words='english')\nX = vec.fit_transform(df['content'])\ny = df['label'].values\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.25, random_state=24, stratify=y)\n\nclf = RandomForestClassifier(n_estimators=100, random_state=42)\nclf.fit(X_train, y_train)\npred = clf.predict(X_test)\n\nacc = accuracy_score(y_test, pred)\nf1 = f1_score(y_test, pred, average='weighted')\nprint('准确率:', round(acc, 4))\nprint('加权F1:', round(f1, 4))\n\ncm = confusion_matrix(y_test, pred)\nprint('混淆矩阵(行=真实, 列=预测):')\nprint('\\n'.join([' '.join(map(str, row)) for row in cm]))\n# 标签: 0生活 1美食 2游戏 3美妆\nprint('美食被误判为游戏的数量:', cm[1][2])\nprint('美妆被漏判为生活的数量:', cm[3][0])",
      },
    ],
  },
  {
    id: "8-7",
    ch: "8",
    no: "07",
    title: "模拟题任务三：LabelImg 标注 + YOLOv8 训练与推理",
    dur: "30分钟",
    tag: "真题演练·本地环境",
    lead: "交通标志数据集（直行/停车让行/左转/右转 4 类）大部分已标注，少量标注不精准，需用 LabelImg 检查补标；然后按卷面参数训练 YOLOv8、评估、推理 6 张测试图。训练和推理必须在比赛机（deepLearn 环境）完成，浏览器跑不了 torch，所以本节给的是可以直接照抄的比赛环境代码。",
    points: [
      "标注子任务要点：开 LabelImg（标签环境启动），打开数据目录选中图片，检查已有边框是否贴合目标，不精准的重新画框；类别必须与 yaml 一致（Straight/Stop/Left/Right），保存格式 YOLO（class x_center y_center width height，归一化坐标）",
      "训练参数按卷面：epochs=15、batch_size=6、img_size=416、workers=0、lr0=0.01、起始权重 yolov8n.pt；训练完成保存 traffic_sign_detect_model.pt",
      "评估输出：mAP@0.5 与 Precision 保留 4 位小数；损失曲线存 train_loss_curve.png（≥300dpi，含图例/标题/坐标轴）",
      "推理：加载模型对测试集 6 张图推理，输出每张的类别、置信度、边界框坐标；结果图存 detect_result_01.png～06.png；平均置信度输出并存 infer_result.txt",
      "data.yaml 路径要指向数据集根目录，本项目给的示例数据里 yaml 已写好 four 类配置",
    ],
    refs: [
      {
        title: "YOLOv8 训练 + 评估（比赛环境运行）",
        code: "from ultralytics import YOLO\n\n# 训练（参数与模拟题卷面一致）\nmodel = YOLO('yolov8n.pt')\nresults = model.train(\n    data='traffic_sign_data.yaml',\n    epochs=15,\n    batch=6,\n    imgsz=416,\n    workers=0,\n    lr0=0.01,\n    project='traffic_sign',\n    name='train'\n)\n\n# 评估：从训练结果加载最佳权重\nbest = YOLO('traffic_sign/train/weights/best.pt')\nmetrics = best.val(data='traffic_sign_data.yaml')\nprint('mAP@0.5: %.4f' % metrics.box.map50)\nprint('Precision: %.4f' % metrics.box.mp)\n\n# 保存训练好的模型文件（卷面命名）\nbest.export(imgsz=416)\n",
      },
      {
        title: "YOLOv8 推理 6 张测试图（比赛环境运行）",
        code: "from ultralytics import YOLO\nimport os\n\nmodel = YOLO('traffic_sign/train/weights/best.pt')\n\ntest_dir = 'traffic_sign_dataset/test/images'\nimgs = sorted(os.listdir(test_dir))[:6]\nnames = model.names   # {0:'Straight',1:'Stop',2:'Left',3:'Right'}\nconfs = []\n\nfor i, fname in enumerate(imgs, start=1):\n    res = model.predict(os.path.join(test_dir, fname), conf=0.25)\n    r = res[0]\n    print('图片 %d: %s' % (i, fname))\n    for box in r.boxes:\n        cls = int(box.cls[0])\n        conf = float(box.conf[0])\n        xyxy = box.xyxy[0].tolist()\n        confs.append(conf)\n        print('  类别%s 置信度%.4f 坐标[%.0f,%.0f,%.0f,%.0f]' % (\n            names[cls], conf, *xyxy))\n    r.save('detect_result_%02d.png' % i)\n\navg = sum(confs) / len(confs)\nprint('平均置信度: %.4f' % avg)\nwith open('infer_result.txt', 'w', encoding='utf-8') as f:\n    f.write('平均置信度: %.4f\\n' % avg)\n",
      },
      {
        title: "损失曲线 300dpi 导出（比赛环境运行）",
        code: "import pandas as pd\nimport matplotlib\nmatplotlib.use('Agg')\nimport matplotlib.pyplot as plt\nplt.rcParams['font.sans-serif'] = ['SimHei']\nplt.rcParams['axes.unicode_minus'] = False\n\n# ultralytics 训练会在 results.csv 记录各 epoch 指标\nres = pd.read_csv('traffic_sign/train/results.csv')\n\nplt.figure(figsize=(8, 5))\nplt.plot(res['epoch'], res['train/box_loss'], label='train box_loss')\nplt.plot(res['epoch'], res['val/box_loss'], label='val box_loss')\nplt.title('YOLOv8 损失曲线')\nplt.xlabel('epoch')\nplt.ylabel('loss')\nplt.legend()\nplt.tight_layout()\nplt.savefig('train_loss_curve.png', dpi=300)\nprint('已保存 train_loss_curve.png (300dpi)')",
      },
    ],
  },
  {
    id: "8-8",
    ch: "8",
    no: "08",
    title: "模拟题任务四：扫地机器人知识库 + Agent 工作流",
    dur: "30分钟",
    tag: "真题演练·Dify操作",
    lead: "大模型任务分两个子任务：先在 Dify 建两个知识库（产品参数库、售后问答库）并召回测试；再建扫地机器人智能客服 Agent，多分支工作流（产品参数 / 售后 / 无关兜底），测试 6 个问题并截图。全程在 Dify 网页界面操作，本节把每一步的操作路径和截图命名列清楚。",
    points: [
      "预检：ollama list 应看到 qwen3:14b-q8_0（或 deepseek-r1:14b-qwen-distill-q8_0）与 bge-m3；Dify 通了 localhost/install 并登录",
      "知识库①：新建『扫地机器人产品参数知识库』，导入 SweeperRobot.csv；嵌入模型选 bge-m3；分块方式『按行分块』；②售后问答库同理导入 SweeperAfterSale.csv",
      "召回测试两问：『扫拖一体机器人的最大吸力是多少？』（产品库）、『扫地机器人越障能力变差怎么办？』（售后库），测试结果要截图",
      "截图命名固定：kb_product.png、kb_aftersale.png、test_product.png、test_aftersale.png；Agent 工作流编辑页截图 workflow.png，三场景测试 test_scene1/2/3.png，最后导出工作流 DSL 文件",
      "工作流分支逻辑：提问含吸力/续航/越障/扫拖/价格 → 产品库；含故障/维修/清洁/配件/续航变差 → 售后库；无关问题 → 固定回复『您好，我是扫地机器人智能客服，仅解答产品相关和售后问题哦，如需其他帮助请联系人工客服～』（原话照抄）",
      "三个测试场景各 2 问：产品『超薄扫地机器人的机身厚度是多少？』『扫地机器人的电池容量有多大？』；售后『扫地机器人报错 E1 怎么处理？』『清洁刷缠头发怎么办？』；无关『今天天气怎么样？』『推荐一款智能手机』",
    ],
    steps: [
      {
        title: "Dify 操作流水（按顺序执行）",
        head: ["步骤", "操作"],
        rows: [
          ["1", "服务器上打开 Docker Desktop，等待引擎就绪"],
          ["2", "cmd 进入 C:\\Program Files\\dify\\dify-1.9.2 的 docker 目录，运行 docker compose 启动命令等待容器全部 up"],
          ["3", "浏览器打开 localhost/install，完成安装或登录（AIServerTest001@Test.com / AIServerTest001）"],
          ["4", "设置中确认 Ollama 模型供应商已启用，添加本地模型：名称 qwen3:14b-q8_0、base_url 按卷面提示（127.0.0.1:11434），向量模型同样添加 bge-m3"],
          ["5", "知识库页新建两个库，分别导入两个 CSV，嵌入模型选 bge-m3，索引方式按行分块，分别做一次召回测试并截图"],
          ["6", "创建 Agent 应用，编排多分支工作流：意图识别节点 → 三个分支（产品参数/售后/无关）→ 各分支检索对应知识库 → LLM 生成（qwen3:14b-q8_0）→ 兜底固定回复"],
          ["7", "测试三个场景共 6 问，逐个截图；导出工作流 DSL 文件，全部文件按卷面命名保存"],
        ],
      },
    ],
  },
  {
    id: "8-9",
    ch: "8",
    no: "09",
    title: "模拟题任务五：智慧社区业务分析",
    dur: "20分钟",
    tag: "真题演练",
    lead: "模拟卷的任务五是业务分析和方案设计，场景：智慧社区服务智能体（快递指引/社区活动咨询/物业报修/生活服务推荐）运行 4 个月后出现报修解答不准、活动信息更新滞后、高峰期响应卡顿、居民满意度低。答题要求与方法在第 7 章已完整拆解，本节只在真题语境下把答题框架收敛成可直接抄写的结构。",
    points: [
      "痛点三类：用户侧（报修解答不准导致投诉率高）、技术侧（活动知识库不更新，检索到过期信息）、业务侧（高峰并发卡顿，无人工兜底路径）",
      "四维度失效分析：响应速度（本地模型推理排队）、回答准确性（知识库覆盖不足 + 幻觉）、并发能力（单实例部署无队列）、知识时效性（知识库无更新机制）",
      "背景价值 ≤200 字：智慧社区建设背景 + 智能体服务现状 + AI 改造必要性 + 预期降本增效",
      "方案：模型 qwen3:14b-q8_0（离线可控）、向量 bge-m3、平台 Dify、数据库 MySQL；工作流五环节意图识别→检索→决策→回答→人工介入；混合架构两条论证（幻觉 / 规则覆盖不到开放问题）",
      "改进方向：知识库版本管理与定时更新、问答分流与缓存、人工反馈闭环",
      "详情回到第 7 章 7-4 节逐条对照",
    ],
  },
  {
    id: "8-10",
    ch: "8",
    no: "10",
    title: "专项摸底考试 2：pandas 实操三连（在线可跑）",
    dur: "30分钟",
    tag: "真题演练·在线运行",
    lead: "专项摸底考试 2 是第一阶段训练的 pandas 实操卷，三道题共 18 分，全部是数据准备模块（任务一 5 分）的同构训练：hotel.csv（客观评分数据）、实验基础设施表（4 楼 + 5 楼两张表）、shopping.csv（1274 条商品数据）。数据已内置，在线可直接跑。",
    points: [
      "题目 6（hotel.csv）：删商圈为空的行存 hotel2_c1_N.csv；删缺失值大于 3 个的列存 hotel2_c2_N.csv；评分空置 0 存 c3；评分空置总平均（保留 1 位小数）存 c4——文件名里的 N 是每步的结果值，文件名随结果变",
      "题目 7（实验基础设施表）：concat 两表成数据集 A，输出记录数（不含表头）；按房间号分组求单价总和；找 511 房间单价最高和最低的品名",
      "题目 8（shopping.csv）：库存 <10 或 >10000 删除；名称含『刷单』『捡漏』删除；含『女装』删除；手机价格区间文本（如 2100-2500）取平均数替换",
      "lab 表是 GBK 编码：pd.read_csv('lab4f.csv', encoding='gbk')，比赛时先确认编码，中文乱码直接查编码参数",
      "所有文件名带 N 的题，考试时用真实结果值命名，交卷截图里要能看到文件名",
    ],
    demos: [
      {
        title: "题目 6：hotel.csv 清洗（在线运行）",
        code: "import pandas as pd\n\ndf = pd.read_csv('hotel.csv')\nprint('原始形状:', df.shape)\n\n# (1) 商圈为空的行删除\nc1 = df.dropna(subset=['shopping'])\nprint('删除商圈为空后剩余:', len(c1), '删除数:', len(df) - len(c1))\n# c1.to_csv('hotel2_c1_%d.csv' % (len(df)-len(c1)), index=False)\n\n# (2) 缺失值大于3个的列删除\nmiss = df.isna().sum()\nbad_cols = list(miss[miss > 3].index)\nprint('删除的列:', bad_cols)\nc2 = df.drop(columns=bad_cols)\n# c2.to_csv('hotel2_c2_' + '_'.join(bad_cols) + '.csv', index=False)\n\n# (3) 评分空置0\nc3 = df.copy()\nc3['score'] = c3['score'].fillna(0)\nprint('评分为空的记录数:', df['score'].isna().sum())\n# c3.to_csv('hotel2_c3_%d.csv' % df['score'].isna().sum(), index=False)\n\n# (4) 评分空置总平均（保留1位小数）\navg = round(df['score'].mean(), 1)\nc4 = df.copy()\nc4['score'] = c4['score'].fillna(avg)\nprint('总平均评分(1位小数):', avg)\n# c4.to_csv('hotel2_c4_%s.csv' % ('%0.1f' % avg,), index=False)",
      },
      {
        title: "题目 7：实验基础设施表合并与分组（在线运行）",
        code: "import pandas as pd\n\nA = pd.concat([\n    pd.read_csv('lab4f.csv', encoding='gbk'),\n    pd.read_csv('lab5f.csv', encoding='gbk')\n], ignore_index=True)\nprint('数据集A记录数(不含表头):', len(A))\n\n# 按房间号分组求单价总和\nsum_by_room = A.groupby('房间号')['单价（元）'].sum()\nprint('各房间单价总和:')\nprint(sum_by_room.to_string())\n\n# 511 房间最高与最低单价的品名\nroom511 = A[A['房间号'] == 511]\nmax_row = room511.loc[room511['单价（元）'].idxmax()]\nmin_row = room511.loc[room511['单价（元）'].idxmin()]\nprint('511 单价最高:', max_row['品名'], max_row['单价（元）'])\nprint('511 单价最低:', min_row['品名'], min_row['单价（元）'])",
      },
      {
        title: "题目 8：shopping.csv 四步清洗（在线运行）",
        code: "import pandas as pd\n\ndf = pd.read_csv('shopping.csv')\nprint('原始形状:', len(df))\n\n# (1) 库存 <10 或 >10000 删除\nc1 = df[(df['库存'] >= 10) & (df['库存'] <= 10000)]\nprint('删除库存异常条数:', len(df) - len(c1))\n# c1.to_csv('shop1_%d.csv' % (len(df)-len(c1)), index=False)\n\n# (2) 名称含刷单/捡漏删除\nmask2 = df['名称'].str.contains('刷单|捡漏', na=False)\nc2 = df[~mask2]\nprint('删除刷单/捡漏条数:', mask2.sum())\n# c2.to_csv('shop2_%d.csv' % mask2.sum(), index=False)\n\n# (3) 含女装删除\nmask3 = df['名称'].str.contains('女装', na=False)\nc3 = df[~mask3]\nprint('删除女装条数:', mask3.sum())\n# c3.to_csv('shop3_%d.csv' % mask3.sum(), index=False)\n\n# (4) 手机价格区间取平均（如 4500.00-6800.00 -> 5650.0）\ndef avg_price(p):\n    p = str(p)\n    if '-' in p:\n        a, b = p.split('-')\n        try:\n            return (float(a) + float(b)) / 2\n        except ValueError:\n            return p\n    return p\n\nc4 = df.copy()\nprint('价格取平均前样例:', c4['价格'].head(3).tolist())\nc4['价格'] = c4['价格'].apply(avg_price)\nprint('价格取平均后样例:', c4['价格'].head(3).tolist())\n# c4.to_csv('shop4_%d.csv' % len(c4), index=False)",
      },
    ],
  },
  {
    id: "8-11",
    ch: "8",
    no: "11",
    title: "JSG 样题要点：回归评估 / KMeans 选 K / ResNet18 / YOLO",
    dur: "30分钟",
    tag: "参考样题",
    lead: "JSG 样题（120 分钟）是三模块结构的另一套参考卷：数据准备（abalone 回归清洗、adult 脱敏、图像增强、标注抽检）、基础算法（回归预测、聚类分析）、深度学习（ResNet18 分类、YOLOv8 检测）。与主赛题重合度很高，其中『回归 RMSE/MAE/R² 对比』『KMeans 肘部法 + 轮廓系数 + DBI 验证』是 JSZ 赛程里也会用到的评估套路，值得掌握。",
    points: [
      "回归评估套路：80/20 划分（random_state=42）；线性回归 + 岭回归（alpha=1.0）+ Lasso（5-fold CV）三连训；输出 RMSE、MAE、R²，表格对比后写选择理由",
      "聚类选 K 套路：StandardScaler 标准化 → 肘部法（不同 K 的 inertia）初选 → 轮廓系数精细选 → Davies-Bouldin 指数交叉验证 → KMeans 聚类 + 2D 散点图（含聚类中心）→ 简述每簇特征",
      "ResNet18 套路：torchvision 预处理（RandomResizedCrop、RandomHorizontalFlip、Normalize）→ 加载预训练 resnet18 改 fc 为 5 类 → tqdm 进度条 + 每轮 train/val 指标 + 保存验证集最优权重 → load_state_dict 恢复并出分类报告",
      "YOLO 套路同 8-7：data.yaml 检查 → 强制 yolov8n.pt 起始权重 → 训练过程实时保存最佳权重 → 测试集推理出图 + 置信度分布分析",
      "本机验证：以上代码用 D:\\python39 环境均实跑通过（torch 2.0.1 + sklearn 1.3.0），可直接抄为比赛模板",
    ],
    refs: [
      {
        title: "回归三连：线性 + 岭 + Lasso（比赛环境运行）",
        code: "import pandas as pd\nfrom sklearn.model_selection import train_test_split, cross_val_score\nfrom sklearn.linear_model import LinearRegression, Ridge, Lasso\nfrom sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score\nimport numpy as np\n\n# abalone_clean.csv 为清洗后的预测 Rings 回归数据\ndf = pd.read_csv('abalone_clean.csv')\nX = df.drop(columns=['Rings'])\ny = df['Rings']\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42)\n\nreport = {}\nfor name, model in [\n    ('LinearRegression', LinearRegression()),\n    ('Ridge(alpha=1.0)', Ridge(alpha=1.0)),\n    ('Lasso(alpha=1.0)', Lasso(alpha=1.0)),\n]:\n    model.fit(X_train, y_train)\n    pred = model.predict(X_test)\n    rmse = mean_squared_error(y_test, pred, squared=False)\n    mae = mean_absolute_error(y_test, pred)\n    r2 = r2_score(y_test, pred)\n    report[name] = [round(rmse, 4), round(mae, 4), round(r2, 4)]\n    print('%s: RMSE=%.4f MAE=%.4f R2=%.4f' % (name, rmse, mae, r2))\n\n# Lasso 5-fold CV\nlasso = Lasso(alpha=1.0)\nscores = cross_val_score(lasso, X, y, cv=5, scoring='r2')\nprint('Lasso 5-fold CV R2: %.4f (+/- %.4f)' % (scores.mean(), scores.std()))",
      },
      {
        title: "KMeans：肘部法 + 轮廓系数 + DBI 选 K（比赛环境运行）",
        code: "from sklearn.cluster import KMeans\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.metrics import silhouette_score, davies_bouldin_score\nimport pandas as pd\n\ndf = pd.read_csv('wholesale_cluster.csv')\nX = StandardScaler().fit_transform(df)\n\nk_range = range(2, 11)\ninertia, sil, dbi = [], [], []\nfor k in k_range:\n    km = KMeans(n_clusters=k, n_init=10, random_state=42)\n    labels = km.fit_predict(X)\n    inertia.append(km.inertia_)\n    sil.append(silhouette_score(X, labels))\n    dbi.append(davies_bouldin_score(X, labels))\n\nfor k, i, s, d in zip(k_range, inertia, sil, dbi):\n    print('K=%d inertia=%.1f silhouette=%.4f DBI=%.4f' % (k, i, s, d))\n# 选 K：轮廓系数越大越好、DBI 越小越好，肘部看惯性拐点",
      },
      {
        title: "ResNet18 五分类训练骨架（比赛环境运行）",
        code: "import torch\nimport torch.nn as nn\nimport torchvision\nimport torchvision.transforms as T\nfrom torch.utils.data import DataLoader\nfrom torchvision.datasets import ImageFolder\nfrom tqdm import tqdm\n\nTRAIN_T = T.Compose([\n    T.RandomResizedCrop(224),\n    T.RandomHorizontalFlip(),\n    T.ToTensor(),\n    T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),\n])\nVAL_T = T.Compose([T.Resize(256), T.CenterCrop(224), T.ToTensor(),\n    T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])\n\ntrs = DataLoader(ImageFolder('flower_data/train', TRAIN_T), batch_size=32, shuffle=True)\nvas = DataLoader(ImageFolder('flower_data/val', VAL_T), batch_size=32)\n\nmodel = torchvision.models.resnet18(pretrained=True)\nmodel.fc = nn.Linear(512, 5)\ndevice = 'cuda' if torch.cuda.is_available() else 'cpu'\nmodel = model.to(device)\ncrit = nn.CrossEntropyLoss()\nopt = torch.optim.Adam(model.parameters(), lr=1e-3)\n\nbest_acc = 0.0\nfor epoch in range(10):\n    model.train()\n    bar = tqdm(trs, desc='Epoch %d' % (epoch + 1))\n    for x, y in bar:\n        x, y = x.to(device), y.to(device)\n        opt.zero_grad()\n        loss = crit(model(x), y)\n        loss.backward()\n        opt.step()\n        bar.set_postfix(loss=loss.item())\n    # 验证\n    model.eval()\n    correct = total = 0\n    with torch.no_grad():\n        for x, y in vas:\n            x, y = x.to(device), y.to(device)\n            correct += (model(x).argmax(1) == y).sum().item()\n            total += y.size(0)\n    acc = correct / total\n    print('Epoch %d val acc %.4f' % (epoch + 1, acc))\n    if acc > best_acc:\n        best_acc = acc\n        torch.save(model.state_dict(), 'best_resnet18.pth')\n\n# 加载最佳权重验证\nmodel.load_state_dict(torch.load('best_resnet18.pth'))\nprint('best acc:', best_acc)",
      },
    ],
  },
];